---
language: elixir
elixir:
  - 1.6.6
  - 1.5
  - 1.4
otp_release:
  - 20.3
  - 19.3
  - 18.3

matrix:
  exclude:
    - elixir: 1.5
      otp_release: 20.3
    - elixir: 1.6.6
      otp_release: 18.3

script:
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.6.6" ]; then mix format --check-formatted --dry-run; fi
  - MIX_ENV=test mix compile && mix test
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.6.6" ] && [ "$TRAVIS_OTP_RELEASE" = "20.3" ]; then mix dialyzer; fi
  - if [ "$TRAVIS_ELIXIR_VERSION" = "1.6.6" ] && [ "$TRAVIS_OTP_RELEASE" = "20.3" ]; then mix coveralls.travis; fi


cache:
  directories:
    - .mix
    - _build
